#Define os serviços que o Docker vai subir
services:
  #Serviço do banco de dados
  database:
    #Imagem ofical do PostgreSQL versão 16
    image: "postgres:16.0-alpine3.18"
    #Carrega as variáveis de ambiente do arquivo .env
    env_file:
      - ../.env.development
    #Mapeia a porta do container para máquina local
    ports:
      - "5432:5432"
